import React from 'react';
import type { SpotlightItem } from '../../src';
import {
  CursorClick,
  TextAa,
  ListBullets,
  CalendarBlank,
  CheckSquare,
  RadioButton,
  ToggleLeft,
  TextAlignLeft,
  SlidersHorizontal,
  UploadSimple,
  Table,
  Cards,
  CaretCircleDown,
  Tabs,
  ChatCircleDots,
  Info,
  Bone,
  Ghost,
  ChartBar,
  UserCircle,
  Tag,
  XSquare,
  Sidebar,
  ArrowsClockwise,
  NavigationArrow,
  DotsThree,
  LinkSimple,
  Bell,
  Warning,
  HourglassMedium,
  CircleNotch,
  LineSegment,
  StackSimple,
  BoundingBox,
  DotsSixVertical,
  MagnifyingGlass,
  PaintBrush,
  Hash,
  Palette,
  Star,
  Password,
  CalendarDots,
  ClockCounterClockwise,
  Rows,
  TreeStructure,
  GridFour,
  CircleHalf,
  Command,
  ArrowSquareOut,
  Layout,
  BellRinging,
  Copy,
  CheckCircle,
  Shield,
} from '@phosphor-icons/react';

const ICON_SIZE = 16;

// ─── Spotlight data ─────────────────────────────────────────────────────────

export const spotlightItems: SpotlightItem[] = [
  // ── Formuláře ───────────────────────────────────────────────────────────
  {
    id: 'button',
    label: 'Button',
    description: 'Primary, secondary a outline varianty',
    category: 'Formuláře',
    icon: <CursorClick size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'input',
    label: 'Input',
    description: 'Textový vstup s ikonou, loading a clear stavy',
    category: 'Formuláře',
    icon: <TextAa size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'select',
    label: 'Select',
    description: 'Výběr ze seznamu hodnot',
    category: 'Formuláře',
    icon: <ListBullets size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'datepicker',
    label: 'DatePicker',
    description: 'Výběr data s kalendářem',
    category: 'Formuláře',
    icon: <CalendarBlank size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'checkbox',
    label: 'Checkbox',
    description: 'Zaškrtávací pole',
    category: 'Formuláře',
    icon: <CheckSquare size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'radio',
    label: 'Radio',
    description: 'Přepínací tlačítko ve skupině',
    category: 'Formuláře',
    icon: <RadioButton size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'switch',
    label: 'Switch',
    description: 'Přepínač zapnuto/vypnuto',
    category: 'Formuláře',
    icon: <ToggleLeft size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'textarea',
    label: 'Textarea',
    description: 'Víceřádkový textový vstup',
    category: 'Formuláře',
    icon: <TextAlignLeft size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'slider',
    label: 'Slider',
    description: 'Posuvný výběr hodnoty',
    category: 'Formuláře',
    icon: <SlidersHorizontal size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'fileupload',
    label: 'FileUpload',
    description: 'Nahrání souborů drag & drop',
    category: 'Formuláře',
    icon: <UploadSimple size={ICON_SIZE} />,
    onSelect: () => {},
  },

  {
    id: 'segmentedcontrol',
    label: 'SegmentedControl',
    description: 'Segmentovaný přepínač s animovaným indikátorem',
    category: 'Formuláře',
    icon: <ToggleLeft size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Zobrazení dat ───────────────────────────────────────────────────────
  {
    id: 'table',
    label: 'Table',
    description: 'Tabulka s řazením a stránkováním',
    category: 'Zobrazení dat',
    icon: <Table size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'card',
    label: 'Card',
    description: 'Obsahová karta',
    category: 'Zobrazení dat',
    icon: <Cards size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'accordion',
    label: 'Accordion',
    description: 'Skládací sekce obsahu',
    category: 'Zobrazení dat',
    icon: <CaretCircleDown size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'tabs',
    label: 'Tabs',
    description: 'Záložkové přepínání obsahu',
    category: 'Zobrazení dat',
    icon: <Tabs size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'tooltip',
    label: 'Tooltip',
    description: 'Informační bublina při hoveru',
    category: 'Zobrazení dat',
    icon: <ChatCircleDots size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'popover',
    label: 'Popover',
    description: 'Plovoucí panel s obsahem',
    category: 'Zobrazení dat',
    icon: <Info size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'skeleton',
    label: 'Skeleton',
    description: 'Placeholder při načítání',
    category: 'Zobrazení dat',
    icon: <Bone size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'emptystate',
    label: 'EmptyState',
    description: 'Stav bez dat',
    category: 'Zobrazení dat',
    icon: <Ghost size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'stat',
    label: 'Stat',
    description: 'Statistická hodnota s popisem',
    category: 'Zobrazení dat',
    icon: <ChartBar size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'avatar',
    label: 'Avatar',
    description: 'Profilový obrázek nebo iniciály',
    category: 'Zobrazení dat',
    icon: <UserCircle size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'tag',
    label: 'Tag / Badge',
    description: 'Štítek a stavový badge',
    category: 'Zobrazení dat',
    icon: <Tag size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Navigace & layout ──────────────────────────────────────────────────
  {
    id: 'modal',
    label: 'Modal',
    description: 'Dialogové okno s překryvem',
    category: 'Navigace',
    icon: <XSquare size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'drawer',
    label: 'Drawer',
    description: 'Postranní vysouvací panel',
    category: 'Navigace',
    icon: <Sidebar size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'breadcrumb',
    label: 'Breadcrumb',
    description: 'Drobečková navigace',
    category: 'Navigace',
    icon: <NavigationArrow size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'pagination',
    label: 'Pagination',
    description: 'Stránkování výsledků',
    category: 'Navigace',
    icon: <DotsThree size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'stepper',
    label: 'Stepper',
    description: 'Krokový průvodce',
    category: 'Navigace',
    icon: <ArrowsClockwise size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'dropdownmenu',
    label: 'DropdownMenu',
    description: 'Rozbalovací nabídka akcí',
    category: 'Navigace',
    icon: <ListBullets size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'link',
    label: 'Link',
    description: 'Odkaz se styly',
    category: 'Navigace',
    icon: <LinkSimple size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'spotlight',
    label: 'Spotlight',
    description: 'Command palette pro vyhledávání',
    category: 'Navigace',
    icon: <MagnifyingGlass size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Feedback ───────────────────────────────────────────────────────────
  {
    id: 'toast',
    label: 'Toast',
    description: 'Notifikační zpráva',
    category: 'Feedback',
    icon: <Bell size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'alert',
    label: 'Alert',
    description: 'Informační banner',
    category: 'Feedback',
    icon: <Warning size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'progress',
    label: 'Progress',
    description: 'Ukazatel průběhu',
    category: 'Feedback',
    icon: <HourglassMedium size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'spinner',
    label: 'Spinner',
    description: 'Indikátor načítání',
    category: 'Feedback',
    icon: <CircleNotch size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Utility ────────────────────────────────────────────────────────────
  {
    id: 'divider',
    label: 'Divider',
    description: 'Oddělovací čára',
    category: 'Utility',
    icon: <LineSegment size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'stack',
    label: 'Stack',
    description: 'Flex layout kontejner',
    category: 'Utility',
    icon: <StackSimple size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'container',
    label: 'Container',
    description: 'Obalovací kontejner s max-width',
    category: 'Utility',
    icon: <BoundingBox size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'draglist',
    label: 'DragList',
    description: 'Přeřaditelný seznam drag & drop',
    category: 'Utility',
    icon: <DotsSixVertical size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Nové formuláře ──────────────────────────────────────────────────────
  {
    id: 'numberinput',
    label: 'NumberInput',
    description: 'Numerický vstup s tlačítky +/−',
    category: 'Formuláře',
    icon: <Hash size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'combobox',
    label: 'Combobox',
    description: 'Vstup s automatickým doplňováním',
    category: 'Formuláře',
    icon: <ListBullets size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'colorpicker',
    label: 'ColorPicker',
    description: 'Výběr barvy s paletou',
    category: 'Formuláře',
    icon: <Palette size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'rating',
    label: 'Rating',
    description: 'Hodnocení hvězdičkami',
    category: 'Formuláře',
    icon: <Star size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'otpinput',
    label: 'OTPInput',
    description: 'Jednorázový kód s oddělenými políčky',
    category: 'Formuláře',
    icon: <Password size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Nové zobrazení dat ─────────────────────────────────────────────────
  {
    id: 'calendar',
    label: 'Calendar',
    description: 'Měsíční kalendář s událostmi',
    category: 'Zobrazení dat',
    icon: <CalendarDots size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'timeline',
    label: 'Timeline',
    description: 'Časová osa událostí',
    category: 'Zobrazení dat',
    icon: <ClockCounterClockwise size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'datalist',
    label: 'DataList',
    description: 'Seznam klíč-hodnota',
    category: 'Zobrazení dat',
    icon: <Rows size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'tree',
    label: 'Tree',
    description: 'Stromová struktura s rozbalováním',
    category: 'Zobrazení dat',
    icon: <TreeStructure size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'datagrid',
    label: 'DataGrid',
    description: 'Pokročilá tabulka s výběrem řádků',
    category: 'Zobrazení dat',
    icon: <GridFour size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'mobiledatacard',
    label: 'MobileDataCard',
    description: 'Mobilní zobrazení dat ve formě karet',
    category: 'Zobrazení dat',
    icon: <GridFour size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'statusbadge',
    label: 'StatusBadge',
    description: 'Stavový indikátor s tečkou',
    category: 'Zobrazení dat',
    icon: <CircleHalf size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Nová navigace ──────────────────────────────────────────────────────
  {
    id: 'commandmenu',
    label: 'CommandMenu',
    description: 'Příkazová paleta se skupinami',
    category: 'Navigace',
    icon: <Command size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'sheet',
    label: 'Sheet',
    description: 'Vysouvací panel z libovolné strany',
    category: 'Navigace',
    icon: <ArrowSquareOut size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'appsidebar',
    label: 'AppSidebar',
    description: 'Skládací postranní panel aplikace',
    category: 'Navigace',
    icon: <Layout size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'sidebaritem',
    label: 'SidebarItem',
    description: 'Navigační položka s rozbalováním',
    category: 'Navigace',
    icon: <Layout size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'navbar',
    label: 'Navbar',
    description: 'Horní navigační lišta',
    category: 'Navigace',
    icon: <Layout size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Nový feedback ──────────────────────────────────────────────────────
  {
    id: 'notification',
    label: 'Notification',
    description: 'Trvalé notifikační bannery v layoutu',
    category: 'Feedback',
    icon: <BellRinging size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'confirmdialog',
    label: 'ConfirmDialog',
    description: 'Potvrzovací dialog',
    category: 'Feedback',
    icon: <CheckCircle size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'copybutton',
    label: 'CopyButton',
    description: 'Tlačítko pro kopírování do schránky',
    category: 'Feedback',
    icon: <Copy size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Hooks ──────────────────────────────────────────────────────────────
  {
    id: 'useTheme',
    label: 'useTheme',
    description: 'Hook pro detekci aktuálního tématu',
    category: 'Hooks',
    icon: <PaintBrush size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'useToast',
    label: 'useToast',
    description: 'Hook pro spouštění toast notifikací',
    category: 'Hooks',
    icon: <Bell size={ICON_SIZE} />,
    onSelect: () => {},
  },
];

// Sort items A-Z within each category, preserving category order
const categoryOrder = ['Formuláře', 'Zobrazení dat', 'Navigace', 'Feedback', 'Utility', 'Hooks'];
spotlightItems.sort((a, b) => {
  const catA = categoryOrder.indexOf(a.category);
  const catB = categoryOrder.indexOf(b.category);
  if (catA !== catB) return catA - catB;
  return a.label.localeCompare(b.label);
});
