import React from 'react';
import type { SpotlightItem } from '../../src';
import {
  CursorClick,
  TextAa,
  ListBullets,
  CalendarBlank,
  CheckSquare,
  RadioButton,
  ToggleLeft,
  TextAlignLeft,
  SlidersHorizontal,
  UploadSimple,
  Table,
  Cards,
  CaretCircleDown,
  Tabs,
  ChatCircleDots,
  Info,
  Bone,
  Ghost,
  ChartBar,
  UserCircle,
  Tag,
  XSquare,
  Sidebar,
  ArrowsClockwise,
  NavigationArrow,
  DotsThree,
  LinkSimple,
  Bell,
  Warning,
  HourglassMedium,
  CircleNotch,
  LineSegment,
  StackSimple,
  BoundingBox,
  DotsSixVertical,
  MagnifyingGlass,
  PaintBrush,
} from '@phosphor-icons/react';

const ICON_SIZE = 16;

// ─── Spotlight data ─────────────────────────────────────────────────────────

export const spotlightItems: SpotlightItem[] = [
  // ── Formuláře ───────────────────────────────────────────────────────────
  {
    id: 'button',
    label: 'Button',
    description: 'Primary, secondary a outline varianty',
    category: 'Formuláře',
    icon: <CursorClick size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'input',
    label: 'Input',
    description: 'Textový vstup s ikonou, loading a clear stavy',
    category: 'Formuláře',
    icon: <TextAa size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'select',
    label: 'Select',
    description: 'Výběr ze seznamu hodnot',
    category: 'Formuláře',
    icon: <ListBullets size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'datepicker',
    label: 'DatePicker',
    description: 'Výběr data s kalendářem',
    category: 'Formuláře',
    icon: <CalendarBlank size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'checkbox',
    label: 'Checkbox',
    description: 'Zaškrtávací pole',
    category: 'Formuláře',
    icon: <CheckSquare size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'radio',
    label: 'Radio',
    description: 'Přepínací tlačítko ve skupině',
    category: 'Formuláře',
    icon: <RadioButton size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'switch',
    label: 'Switch',
    description: 'Přepínač zapnuto/vypnuto',
    category: 'Formuláře',
    icon: <ToggleLeft size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'textarea',
    label: 'Textarea',
    description: 'Víceřádkový textový vstup',
    category: 'Formuláře',
    icon: <TextAlignLeft size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'slider',
    label: 'Slider',
    description: 'Posuvný výběr hodnoty',
    category: 'Formuláře',
    icon: <SlidersHorizontal size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'fileupload',
    label: 'FileUpload',
    description: 'Nahrání souborů drag & drop',
    category: 'Formuláře',
    icon: <UploadSimple size={ICON_SIZE} />,
    onSelect: () => {},
  },

  {
    id: 'segmentedcontrol',
    label: 'SegmentedControl',
    description: 'Segmentovaný přepínač s animovaným indikátorem',
    category: 'Formuláře',
    icon: <ToggleLeft size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Zobrazení dat ───────────────────────────────────────────────────────
  {
    id: 'table',
    label: 'Table',
    description: 'Tabulka s řazením a stránkováním',
    category: 'Zobrazení dat',
    icon: <Table size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'card',
    label: 'Card',
    description: 'Obsahová karta',
    category: 'Zobrazení dat',
    icon: <Cards size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'accordion',
    label: 'Accordion',
    description: 'Skládací sekce obsahu',
    category: 'Zobrazení dat',
    icon: <CaretCircleDown size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'tabs',
    label: 'Tabs',
    description: 'Záložkové přepínání obsahu',
    category: 'Zobrazení dat',
    icon: <Tabs size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'tooltip',
    label: 'Tooltip',
    description: 'Informační bublina při hoveru',
    category: 'Zobrazení dat',
    icon: <ChatCircleDots size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'popover',
    label: 'Popover',
    description: 'Plovoucí panel s obsahem',
    category: 'Zobrazení dat',
    icon: <Info size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'skeleton',
    label: 'Skeleton',
    description: 'Placeholder při načítání',
    category: 'Zobrazení dat',
    icon: <Bone size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'emptystate',
    label: 'EmptyState',
    description: 'Stav bez dat',
    category: 'Zobrazení dat',
    icon: <Ghost size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'stat',
    label: 'Stat',
    description: 'Statistická hodnota s popisem',
    category: 'Zobrazení dat',
    icon: <ChartBar size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'avatar',
    label: 'Avatar',
    description: 'Profilový obrázek nebo iniciály',
    category: 'Zobrazení dat',
    icon: <UserCircle size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'tag',
    label: 'Tag / Badge',
    description: 'Štítek a stavový badge',
    category: 'Zobrazení dat',
    icon: <Tag size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Navigace & layout ──────────────────────────────────────────────────
  {
    id: 'modal',
    label: 'Modal',
    description: 'Dialogové okno s překryvem',
    category: 'Navigace',
    icon: <XSquare size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'drawer',
    label: 'Drawer',
    description: 'Postranní vysouvací panel',
    category: 'Navigace',
    icon: <Sidebar size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'breadcrumb',
    label: 'Breadcrumb',
    description: 'Drobečková navigace',
    category: 'Navigace',
    icon: <NavigationArrow size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'pagination',
    label: 'Pagination',
    description: 'Stránkování výsledků',
    category: 'Navigace',
    icon: <DotsThree size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'stepper',
    label: 'Stepper',
    description: 'Krokový průvodce',
    category: 'Navigace',
    icon: <ArrowsClockwise size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'dropdownmenu',
    label: 'DropdownMenu',
    description: 'Rozbalovací nabídka akcí',
    category: 'Navigace',
    icon: <ListBullets size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'link',
    label: 'Link',
    description: 'Odkaz se styly',
    category: 'Navigace',
    icon: <LinkSimple size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'spotlight',
    label: 'Spotlight',
    description: 'Command palette pro vyhledávání',
    category: 'Navigace',
    icon: <MagnifyingGlass size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Feedback ───────────────────────────────────────────────────────────
  {
    id: 'toast',
    label: 'Toast',
    description: 'Notifikační zpráva',
    category: 'Feedback',
    icon: <Bell size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'alert',
    label: 'Alert',
    description: 'Informační banner',
    category: 'Feedback',
    icon: <Warning size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'progress',
    label: 'Progress',
    description: 'Ukazatel průběhu',
    category: 'Feedback',
    icon: <HourglassMedium size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'spinner',
    label: 'Spinner',
    description: 'Indikátor načítání',
    category: 'Feedback',
    icon: <CircleNotch size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Utility ────────────────────────────────────────────────────────────
  {
    id: 'divider',
    label: 'Divider',
    description: 'Oddělovací čára',
    category: 'Utility',
    icon: <LineSegment size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'stack',
    label: 'Stack',
    description: 'Flex layout kontejner',
    category: 'Utility',
    icon: <StackSimple size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'container',
    label: 'Container',
    description: 'Obalovací kontejner s max-width',
    category: 'Utility',
    icon: <BoundingBox size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'draglist',
    label: 'DragList',
    description: 'Přeřaditelný seznam drag & drop',
    category: 'Utility',
    icon: <DotsSixVertical size={ICON_SIZE} />,
    onSelect: () => {},
  },

  // ── Hooks ──────────────────────────────────────────────────────────────
  {
    id: 'useTheme',
    label: 'useTheme',
    description: 'Hook pro detekci aktuálního tématu',
    category: 'Hooks',
    icon: <PaintBrush size={ICON_SIZE} />,
    onSelect: () => {},
  },
  {
    id: 'useToast',
    label: 'useToast',
    description: 'Hook pro spouštění toast notifikací',
    category: 'Hooks',
    icon: <Bell size={ICON_SIZE} />,
    onSelect: () => {},
  },
];
